### ISSUE TITLE
The plugin hard codes the currency as $

### ISSUE THREAD

**Issue by mikelittle** [curtismchale/Coupons-for-Gravity-Forms#12]
The discounted total is output preceded by a dollar sign '$'. It should make use of the currency configured in Gravity Forms.

I'm not familiar enough with Git or GitHub to create a pull request (if that's what I'm supposed to do) but I have a diff file which can be applied with patch to correct the problem. Ii's only a two line change.

```
--- coupons-for-gravityforms.php.original   2013-02-09 00:47:41.000000000 +0000
+++ coupons-for-gravityforms.php    2013-02-09 00:46:59.000000000 +0000
@@ -199,7 +199,8 @@

                         var newPrice = ( total - discount );
                         jQuery( totalField ).val( newPrice );
-                        jQuery( '.ginput_total_'+formID ).html( '$'+newPrice );
+                       var currency = new Currency( gf_global.gf_currency_config );
+                        jQuery( '.ginput_total_'+formID ).html( currency.toMoney( newPrice ) );

                         couponApplied = true;
                     } else {
```

**Comment by curtismchale** [comment]
I'm happy to merge a pull request. For a two line change you can just navigate to the file in Github and edit it. You'll create a 'fork' to make your change. Then just click the pull request button.

Or put the 2 link change in a Gist and link it here.
