### ISSUE TITLE
Required fields becoming not required

### ISSUE THREAD

**Issue by moberdier** [curtismchale/Coupons-for-Gravity-Forms#17]
When I submit a coupon code, fields that are supposed to be required are being allowed as blank submissions. Hence, my required fileds, such as "email" and "name" are becoming regular non-required fields.

**Comment by curtismchale** [comment]
You shouldn't use this anymore, Gravity Forms has coupons built in. I'm not fixing anything in it.

In fact it's going to be deleted.
