### ISSUE TITLE
Add-on seems to no longer work. 'No such coupon' error

### ISSUE THREAD

**Issue by whathedilly45** [curtismchale/Coupons-for-Gravity-Forms#18]
This add-on worked perfectly a year ago and was much appreciated! Today, a client is emailing me asking why discount codes don't work anymore. I didn't change anything, but, suddenly, when customers try to use a discount code, it works, all the way up to submitting payment info, at which point, a "No such coupon" error appears, and the purchase is declined. Thanks for any help you might be able to give.

**Comment by curtismchale** [comment]
Sorry I don’t have much help to give. I haven’t looked at this in years.
