### ISSUE TITLE
Instructions are unclear regarding "$coupon"

### ISSUE THREAD

**Issue by clarkewd** [curtismchale/Coupons-for-Gravity-Forms#4]
I understand most of the instructions in the Readme file but one of the lines is unclear:

> You just enter the coupons in the $coupon variable in the code.

What does this mean? Where is this referring to - the form editor, the single line text input, the theme's php code, the coupons under settings?

**Comment by atlcodecommandr** [comment]
I too am curious about this

**Comment by clarkewd** [comment]
@garronte i think you have to create two single line text fields and set the css class in the advanced tab for both of them. one needs to be gfcoupon and one needs to be gfdiscount. the second one will be hidden to the end user but will be used in calculation. if you don't have both of these added to your form then nothing special will show up. if you have them both added the first one will have an apply button and the second one should be hidden. i still don't know what the $coupon thing was referring to but I figured out I didn't really need to do anything with it.

**Comment by curtismchale** [comment]
Sorry the directions aren't as clear as they should be. Some of theme are actually left over from an older version. I'll be adding an export of a working Form next week once I'm on vacation and have some time for personal projects.

I'll also put together a video setup tutorial.

**Comment by atlcodecommandr** [comment]
I have both fields and the form looks right, but it doesnt seem like its working. curtis let me know when you set that up. and if anybody knows where to put the $coupon for the meantime it would be great. 

http://fdasolutionsgroup.com/sample-page/

**Comment by clarkewd** [comment]
You have the apply button and so you've done it correctly. You'll need to add a coupon which I think is under the "Settings" menu in the Wordpress admin and then you should be able to apply a discount. Forget about $coupon that is nonsense in the readme file and hopefully curtis will update / remove it.

<img src="http://img853.imageshack.us/img853/4135/picturedt.png" />

**Comment by atlcodecommandr** [comment]
I created TESTING2012 to take off $10 but its not working

**Comment by clarkewd** [comment]
notes on creating coupons:

1) the coupon must be set as draft and not published
2) make sure you have the title / name of the coupon set correctly - note the field that says something like "this is what the user types in"
3) you probably selected percentage or dollar correctly

**Comment by atlcodecommandr** [comment]
https://dl.dropbox.com/u/3202624/Screen%20Shot%202012-10-16%20at%2010.33.53%20PM.png

**Comment by clarkewd** [comment]
based on your screenshot:

 <img src="http://img35.imageshack.us/img35/9897/screen20shot20201210162.png" alt="Screen%20Shot%202012-10-16%20at%2010.33.53%20PM.png" />

maybe try clicking "save draft" and also please note that your coupon code the user would enter would be "a"

**Comment by atlcodecommandr** [comment]
the draft is saved, and i tried putting in a but its not working. I' feel like i followed all the steps btu its not updating the total

**Comment by clarkewd** [comment]
yeah i noticed there is an error in the javascript of the page (probably because a blank response when it tries to lookup "a" as a coupon). i would try changing it to a $ instead of % discount and maybe make the coupon name something longer. maybe add a second coupon. maybe check your php error log.

**Comment by atlcodecommandr** [comment]
yeah I can't figure it out. just reinstalled everything and i'm still getting:

SyntaxError: JSON.parse: unexpected end of data
[Break On This Error]   

var return_value = JSON.parse( response );

oh well hopefully curtis will have the update coming up

**Comment by curtismchale** [comment]
The documentation has been updated to actually be correct and there is now a sample Form included that works. I'll break out the JS error in to a support ticket.

**Comment by clarkewd** [comment]
There is a javascript error but I believe it is because the javascript is expecting a non-empty response. This could be fixed but the response he's getting on his form indicates that there is a problem with the query happening on the ajax call
