### ISSUE TITLE
Database lookup validation for mass coupon code upload

### ISSUE THREAD

**Issue by askchrisedwards** [curtismchale/Coupons-for-Gravity-Forms#9]
I was attempting to try to add some code referenced by Chris Hajer at Gravity forms here -http://www.gravityhelp.com/forums/topic/database-look-up-validation#post-43732

His snippet here http://pastebin.com/7ANQh6Rc allows you to use a text file with a list to validate against within the gravity forms field.

I was looking to implement this in some way so I can upload hundreds of coupon codes that are unique for usage one time only and the those specific codes would be invalidated if used again.  Or perhaps a parameter can be added on how many times the usage is allowed per code as well.

Any way we can implement this?

**Comment by curtismchale** [comment]
The coupons are mapped to a Custom Post Type so you could build a standard WordPress XML file to import the coupons just as you'd have to import a CPT.

**Comment by askchrisedwards** [comment]
Any examples you could provide off the top of your head?

**Comment by MG7282** [comment]
Do you know which tables need to be updated?  I just imported a bunch of coupons and they don't work.
